// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using destinos.Data;

#nullable disable

namespace destinos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110180541_migration03")]
    partial class migration03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("destinos.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino_nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("destino_preco");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino_url");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salvador",
                            Preco = 799.99m,
                            Url = "https://images-ext-2.discordapp.net/external/W7r1kRZ6dZP1DYw6VngZXZmAgAi9zq-ffmZIcpi3QM8/%3Fw%3D280%26h%3D187%26c%3D7%26r%3D0%26o/https/th.bing.com/th/id/OIP.8xXpo17vRbI0NpVdgyYoOAHaE7?format=webp&width=251&height=168"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "São Paulo",
                            Preco = 899.99m,
                            Url = "https://images-ext-2.discordapp.net/external/W7r1kRZ6dZP1DYw6VngZXZmAgAi9zq-ffmZIcpi3QM8/%3Fw%3D280%26h%3D187%26c%3D7%26r%3D0%26o/https/th.bing.com/th/id/OIP.8xXpo17vRbI0NpVdgyYoOAHaE7?format=webp&width=251&height=168"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rio de Janeiro",
                            Preco = 999.99m,
                            Url = "https://images-ext-2.discordapp.net/external/W7r1kRZ6dZP1DYw6VngZXZmAgAi9zq-ffmZIcpi3QM8/%3Fw%3D280%26h%3D187%26c%3D7%26r%3D0%26o/https/th.bing.com/th/id/OIP.8xXpo17vRbI0NpVdgyYoOAHaE7?format=webp&width=251&height=168"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Paraiba",
                            Preco = 699.99m,
                            Url = "ddddd.png"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Minas Gerais",
                            Preco = 1099.99m,
                            Url = "eeeee.png"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Acre",
                            Preco = 759.99m,
                            Url = "fffff.png"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Pará",
                            Preco = 1200.00m,
                            Url = "ggggg.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
