// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using destinos.Data;

#nullable disable

namespace destinos.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("destinos.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino_nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("destino_preco");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("destino_url");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salvador",
                            Preco = 799.99m,
                            Url = "https://img.freepik.com/free-photo/long-shot-bahia-nautico-museum-salvdor-brazil-cloudy-blue-skies_181624-19965.jpg?w=740&t=st=1704910800~exp=1704911400~hmac=7b29602f804eadf85c1aa194c8341e031793c80a230b94d2d8992be685d65e4b"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "São Paulo",
                            Preco = 899.99m,
                            Url = "https://img.freepik.com/free-photo/complex-aerial-view-city_23-2148975280.jpg?w=740&t=st=1704910907~exp=1704911507~hmac=759676c01827d187c2d6fe90e7705c2888519d0cd26587d49d56c30ad9618e60"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Rio de Janeiro",
                            Preco = 999.99m,
                            Url = "https://img.freepik.com/free-photo/landscape-rio-de-janeiro-surrounded-by-sea-blue-sky-brazil_181624-17265.jpg?w=740&t=st=1704910969~exp=1704911569~hmac=b0a3bd03158cbf1952e175bc97642dd8c54ba8d13061b02f5e51f6b7bba203ca"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Paraiba",
                            Preco = 699.99m,
                            Url = "https://img.freepik.com/free-photo/morning-light-sonoran-desert-scottsdale-arizona_181624-48339.jpg?w=740&t=st=1704911051~exp=1704911651~hmac=de860a086becd28ab0fcedb8363da480cd1957e7411171d7c84d5931f372a527"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Minas Gerais",
                            Preco = 1099.99m,
                            Url = "https://img.freepik.com/premium-photo/taquaral-lagoon-campinas-view-from-portugal-park-sao-paulo-brazil_361869-578.jpg?w=826"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Santos",
                            Preco = 759.99m,
                            Url = "https://img.freepik.com/free-photo/boat-goes-blue-sea-deep-blue-sky_1304-4974.jpg?w=740&t=st=1704911307~exp=1704911907~hmac=6ff0da3b8d1709d42ac2f694c7e80956d9384ec7ac01ba0d44b697c6e3a38fd9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
